name: R Package Validation report

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      r-version:
        description: 'The version of R to use'
        default: '4.0'
        required: false
        type: string
  release:
    types: [published]

jobs:
  r-pkg-validation:
    name: Generate
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/dgrassellyb/admiralci-${{ inputs.r-version }}:latest"
    defaults:
      run:
        working-directory: /workspace
    # Set Github token permissions
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REPOS: 'https://packagemanager.posit.co/cran/2021-03-31/'
    permissions:
      contents: write
      packages: write
      deployments: write
    steps:
      ##################### BEGIN boilerplate steps #####################
      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v5.4

      - name: Checkout repo (PR) 🛎
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ steps.branch-name.outputs.head_ref_branch }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Checkout repository
        uses: actions/checkout@v3
        if: github.event_name != 'pull_request'
        with:
          ref: ${{ steps.branch-name.outputs.head_ref_branch }}

      - name: Copy repo into workspace
        run: |
          ls /__w/admiral/admiral
          admiral_dir="/__w/admiral/admiral"
          rm -rf "${admiral_dir}/renv"
          rm "${admiral_dir}/renv.lock"
          cp -r "${admiral_dir}/." /workspace
          ls -al /workspace
          git status /workspace
          # get that renv.lock is identical
          git config --global --add safe.directory /workspace
          diff=$(git diff /workspace/renv.lock)
          echo $diff # TODO: check differences renv.lock to be sure docker im not outdated ? (renv.lock of admiral pointing on r4.0 ..)
        shell: bash

      - name: Normalize inputs
        id: normalizer
        run: |
          R_VERSION="${{ inputs.r-version }}"
          if [ "$R_VERSION" == "" ]
          then {
            R_VERSION="4.0"
          }
          fi
          echo "R_VERSION=$R_VERSION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.staged.dependencies
          key: staged-deps

      - name: Run Staged dependencies
        uses: insightsengineering/staged-dependencies-action@v1
        with:
          run-system-dependencies: true
          enable-check: false
          cran-repos: "RSPM=${{ env.R_REPOS }}"
          path: /workspace
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      ##################### END boilerplate steps #####################

      - name: Build report
        uses: insightsengineering/thevalidatoR@v1.2.4
        id: validation
        with:
          disable_install_dev_deps: true
          report_pkg_dir: /workspace
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload report to release
        if: success()
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ steps.validation.outputs.report_output_filename }}
          asset_name: ${{ steps.validation.outputs.report_output_filename }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          overwrite: false
